cmd/root.go, cmd/root_test.go, internal/proxy/proxy.go, internal/proxy/proxy_test.go, tests/alloydb_test.go
This is an adaptation from https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1182
=> feat: add support for unix sockets

.github/labels.yml, .github/trusted-contribution.yml, .github/workflows/lint.yaml, .github/workflows/tests.yaml
Adding WIF as credentials source for integration tests. Adding `tests: run` label to trigger builds as well.
=> chore(ci): add WIF for integration tests

cmd/root.go, cmd/root_test.go, internal/proxy/proxy.go, internal/proxy/proxy_test.go
This is a port of https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1247
=> chore: move dialer options to proxy.Config

cmd/root.go, cmd/root_test.go, internal/proxy/proxy.go, internal/proxy/proxy_test.go
This is a port of https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1245
=> fix: resolve data race on closing client

cmd/root.go, cmd/root_test.go, internal/proxy/alignment_test.go, internal/proxy/proxy.go, internal/proxy/proxy_test.go
This is a port of https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1240
=> feat: add max connections flag

internal/proxy/proxy.go
This is a port of
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1505.
=> fix: correct error check in check connections

internal/proxy/proxy.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1480.
=> chore: use read-only pattern in proxy

.golangci.yml, cmd/root.go, internal/healthcheck/healthcheck_test.go, internal/proxy/fuse_test.go, internal/proxy/other_test.go, internal/proxy/proxy.go, internal/proxy/proxy_test.go, tests/alloydb_test.go, tests/connection_test.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1461.
=> chore: improve golangci config

cmd/root.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1490.
=> chore: correct internal docstring

internal/proxy/proxy_test.go
=> chore: fix flakey close test

tests/common_test.go
=> chore: fix race condition in proxy exec

Dockerfile.alpine, Dockerfile.bullseye, Dockerfile.buster
Port of [#1680](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1680)
=> fix: build statically linked binaries

README.md
Adding README section for metrics and tracing.
=> docs: add metrics and tracing to README

.github/workflows/cover.yaml, .github/workflows/labels.yaml, .github/workflows/lint.yaml, .github/workflows/sample-tests.yaml, .github/workflows/tests.yaml
=> ci: update workflow to read-only and pin shas

internal/proxy/proxy_test.go
=> chore: fix flaky test

cmd/root.go, cmd/root_linux_test.go, go.mod, go.sum
=> feat: Add support for systemd notify

cmd/root.go, cmd/wait_test.go
=> feat: add wait command support

.github/workflows/sample-tests.yaml, examples/python/app.py, examples/python/requirements.txt
Replace `before_first_request` with `before_request`.
=> chore: replace deprecated `before_first_request`

tests/alloydb_test.go, tests/connection_test.go
Fixes #544
Fixes #543
Fixes #541 
Fixes #533
=> chore: use sequential ports to avoid 5432 conflicts

cmd/root.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2105
=> docs: improve documentation for subcommand

.github/release-please.yml, README.md
Now with every release, release please will update the README to include the latest version.
Fixes #556
=> docs: update version in README automatically

.github/release-please.yml, cmd/root.go
Add where to find third party license info to help message.
=> chore: add licenses info to help message

cmd/root.go
Use inline annotation for release-please to update the version in the URL inside the proxy help message.
Related to https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/2145
=> chore: Use inline annotation for release-please to update version

Dockerfile.bullseye, Dockerfile.buster
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2159
=> feat: use Google managed base images

Dockerfile.bookworm, README.md
Fixes https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/issues/669
=> feat: replace buster with bookworm container

.github/workflows/govulncheck.yaml, .github/workflows/lint.yaml, .github/workflows/sample-tests.yaml, .github/workflows/tests.yaml
=> chore: fix env var and pull request usage

examples/k8s-sidecar/README.md, examples/k8s-sidecar/direct_connection_deployment.yaml, examples/k8s-sidecar/proxy_sidecar_deployment.yaml
=> docs: add GKE connection example

README.md
Related to https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/2211.
=> docs: clarify Artifact Registry support

.github/workflows/codeql.yml, .github/workflows/cover.yaml, .github/workflows/govulncheck.yaml, .github/workflows/lint.yaml, .github/workflows/sample-tests.yaml, .github/workflows/tests.yaml, go.mod
=> chore: update to Go 1.23
