GoogleCloudPlatform/alloydb-auth-proxy

- README.md
- cmd/root.go
- cmd/root_test.go
- internal/healthcheck/healthcheck.go
- internal/healthcheck/healthcheck_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
This is an adaptation of https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1271.
> feat: add support for health-check flag

- cmd/root.go
- cmd/root_test.go
This is an adaptation of https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1280.
> fix: make Prometheus namespace optional

- .github/workflows/tests.yaml
By explicitly configuring `shell: bash` in test step it enables `set -eo pipefail` ([documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)) which means errors in left side of pipe will no longer be suppressed by the success of the right side of the pipe.
```yaml
go test -race -v ./... | tee test_results.txt
```
Additionally, with new `pipefail` being set, if line that runs the test `go test -race -v ./... | tee test_results.txt` fails (i.e. a test fails) than this causes an exit code and for the line below it `go-junit-report ...` not to be run which in turn disables flakybot from working as it requires XML sponge log.
By moving the convert XML functionality to its own step in the workflow we can make …
> chore: fix piped test errors being suppressed

- cmd/root.go
In Kubernetes, the convention is to bind HTTP probes and Prometheus endpoints to 0.0.0.0 (both lo and eth0). Since people might want to run this code on a GCE VM, default to localhost, but otherwise support binding to both interfaces.
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1365.
> fix: support configuration of HTTP server address

- internal/proxy/proxy_test.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1329.
Fixes #117.
> chore: check all connections for io.EOF

- internal/proxy/proxy_test.go
This is port of https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1293.
> chore: increase wait time to ensure TCP connections

- .build/bullseye.yaml
The work to restore this is tracked here: https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/issues/175.
> chore: disable bulleye arm build

- .envrc.example
- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
- tests/alloydb_test.go
- tests/connection_test.go
This is a port of
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1433.
> feat: add support for JSON credentials

- .github/workflows/tests.yaml
- internal/proxy/fuse.go
- internal/proxy/fuse_freebsd.go
- internal/proxy/fuse_openbsd.go
- internal/proxy/proxy_other.go
- internal/proxy/unix.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1442.
> fix: restore openbsd and freebsd support

- .envrc.example
- .github/workflows/tests.yaml
- cmd/root.go
- cmd/root_test.go
- go.mod
- go.sum
- internal/proxy/proxy.go
- tests/alloydb_test.go
- tests/connection_test.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1460.
> feat: add support for service account impersonation

- cmd/root.go
Fixes #138.
This is also a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1479.
> docs: improve long help in CLI output

- cmd/root.go
This is a port of
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1515.
> feat: add quiet flag

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
Parses the instance URI when the proxy starts, failing if it's not in the correct format. 
[bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose) 
before writing your code!  That way we can discuss the change, evaluate 
designs, and agree on the general idea.
- Fixes #186
> feat: fail on startup if instance uri is invalid

- internal/healthcheck/healthcheck_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
Uses "project.region.cluster.instance" instead of the full instance URI when logging for a more compact reference. 
example:
```sh
2022/12/13 23:27:56 [proj.region.clust.inst] client closed the connection
2022/12/13 23:27:56 [proj.region.clust.inst] Listening on 127.0.0.1:5000
2022/12/13 23:27:56 [proj.region.clust.inst1] Listening on 127.0.0.1:6000
2022/12/13 23:27:56 [proj.region.clust.inst2] Listening on 127.0.0.1:6001
```
Depends on #210
[bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose) 
before writing your code!  That way we can discuss the change, evaluate 
designs, and agree on the general idea.
- Fixes #26
> feat: use shorter instance uri when logging

- cmd/root.go
- internal/healthcheck/healthcheck.go
- internal/healthcheck/healthcheck_test.go
- internal/proxy/fuse_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1496.
> feat: add support for min ready instances

- cmd/errors.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1530.
> fix: return correct exit code on SIGTERM

- cmd/root.go
- cmd/root_test.go
This is a port of
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1542 and https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1561.
> feat: add support for user-agent configuration

- cmd/root_test.go
- internal/proxy/proxy.go
Formatting the URI into an instance name when reporting an error should not hide the real error. Also, 
avoid port conflict in root_test.go.
> fix: report the real error when newSocketMount() fails

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
This adds a new parameter unix-socket-path to instances to specify the precise unix socket path.
For example, this command line:
$ alloydb-auth-proxy projects/proj/locations/region/clusters/clust/instances/inst?unix-socket-path=/var/cloudsql/mydb 
Will open a unix socket to the database at the path /var/cloudsql/mydb.
This is different than the existing parameter unix-socket which automatically appends the instance name to the path.
Fixes https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1573
This is a port of cloud-sql-proxy issue PR https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1623
> feat: add support for unix-socket-path instance parameter.

- README.md
- cmd/errors.go
- cmd/root.go
- cmd/root_linux_test.go
- cmd/root_test.go
- internal/proxy/proxy.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1624.
> feat: add support for quitquitquit endpoint

- internal/healthcheck/healthcheck.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1657.
> fix: honor request context in readiness check

- tests/common_test.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1656.
> chore: show all errors in proxy tests

- cmd/root.go
- internal/log/log.go
Porting over https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1750
> fix: allow `--structured-logs` and `--quiet` flags together

- .build/release_artifacts.sh
Adding additional tags to docker images.
Currently we only tag builds with a single tag such as `1.3.2-alpine`
This PR will result in additional tags such as `alpine`, `1.3-alpine`, and `1-alpine`.
The benefit is users who want to always pull the latest alpine build of the Proxy can now just pull the `alpine` tag etc.
> build: add shared tags to docker images

- Dockerfile
- Dockerfile.alpine
- Dockerfile.bullseye
- Dockerfile.buster
Port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2045 to add label to docker images that allows dependabot/renovate version bumps on docker images.
> chore: LABEL Dockerfiles with URL of source repo

- .github/renovate.json
Leverage https://docs.renovatebot.com/modules/manager/#managers to group dep updates.
This will allow all base image SHA bumps to be grouped.
> chore: group deps by matchManagers

- .github/workflows/sample-tests.yaml
At some point we change the name of this secret but forgot to update sample-tests.
Related to #530
> chore: change secret name

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
Use pointer `*bool` for auto IAM authn instance config property. This will allow for unified `parseBoolOpt` for config arguments when introducing public ip.
> chore: use pointer for AutoIAMAuthn instance config

- .build/gcs_upload.yaml
- .github/workflows/codeql.yml
- .github/workflows/cover.yaml
- .github/workflows/govulncheck.yaml
- .github/workflows/lint.yaml
- .github/workflows/sample-tests.yaml
- .github/workflows/tests.yaml
- go.mod
- go.sum
This commit updates all CI builds to use Go 1.22 by default.
In addition, we change the Go version in go.mod. This means any builds of the Proxy must use Go 1.22. Since we don't ship a public API in Go effectively, this is a not a user facing change.
> chore: bump to Go 1.22

- README.md
Java Connector missing from README, adding it
> chore: add Java Connector to README

- README.md
- cmd/config_test.go
- cmd/root.go
- cmd/root_test.go
- cmd/testdata/config-json.json
- cmd/testdata/config-toml.toml
- cmd/testdata/config-yaml.yaml
- cmd/testdata/two-instances.toml
- internal/proxy/proxy.go
This is a port of two commits:
- https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2106
- https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2130
Fixes #590
> feat: add support for a config file

- Dockerfile.bullseye
- Dockerfile.buster
The cloud-marketplace-containers project is a public mirror of cloud-marketplace. Using a public mirror makes it possible for renovate to monitor for new versions. The non-public version otherwise breaks the dependency update process.
> fix: switch to public mirrors of base containers

- internal/proxy/proxy_other.go
- internal/proxy/proxy_other_test.go
If the FUSE mount has not succeeded due to misconfiguration, the Proxy should still shutdown without panicing.
Related to https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/2013
> fix: ensure graceful shutdown on fuse error

- cmd/root.go
- internal/healthcheck/healthcheck.go
- internal/healthcheck/healthcheck_test.go
The readiness probe should not depend on downstream connections. Doing so can cause unwanted downtime. See [1]. This commit removes all dialing of downstream database servers as a result.
In addition, after the Proxy receives a SIGTERM or SIGINT, the readiness check will now report an unhealthy status to ensure it is removed from circulation before shutdown completes.
[1]: https://github.com/zegl/kube-score/blob/master/README_PROBES.md#readinessprobe
> fix: don't depend on downstream in readiness check

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
When clients run the Proxy in environments where the CPU may be throttled, the background connection info refresh operation can fail to complete, causing connection errors. This commit introduces an option for a lazy refresh. Connection info is retrieved on an as needed-basis and cached based on the associated certificate's expiration. No background goroutine runs, unlike the default refresh ahead cache.
Enable it like so:
./alloydb-auth-proxy <INSTANCE_URI> --lazy-refresh
A lazy refresh may result in increased latency (more requests will be subject to waiting for the refresh to complete), but gains in reliability.
Fixes #625
> feat: add support for a lazy refresh (#2184)

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
Add support for seeding the connection info cache with static certificates and IP addresses. This is useful in development contexts and should otherwise be considered a non-production feature.
With this commit, callers may now provide the path to a JSON file which contains an RSA key pair, IP addresses, and certificate chains for any number of AlloyDB instances.
NOTE: the file format is subject to breaking changes. As such this feature should be considered for development only.
> feat: support static connection info

- internal/proxy/fuse_test.go
- internal/proxy/proxy_other.go
Ignore context passed into `Lookup` as it can be cancelled by
interrupts in go-fuse. Instead create a new context when `Lookup`
is invoked.
Fixes #674
> fix: ignore go-fuse ctx in Lookup

- .github/labels.yml
- .github/workflows/codeql.yml
- .github/workflows/govulncheck.yaml
- .github/workflows/lint.yaml
- .github/workflows/sample-tests.yaml
- .github/workflows/scorecard.yml
- .github/workflows/tests.yaml
The pull request target is inherently fragile and prone to security vulnerabilities. The only reason we used it was to put our testing project name, our testing service account email (not key), and WIF provider pool ID into secrets. In fact, all three of those values aren't necessarily secrets and work just as well in environment variables.
We will still need to vet a PR before clicking "approve and run," but that's a much smaller attack surface area than pull request target.
> ci: remove pull request target usages

- cmd/errors.go
- cmd/root.go
- internal/proxy/proxy.go
Adds a new flag `exit-zero-on-sigterm` to exit with a 0 exit code when SIGTERM is received. This is a port of CloudSQL's `exit-on-zero-sigterm` (https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1870). Likewise, it is needed for applications that think that an exit code 143 is an error when it is not, and this provides users an easy workaround.
Fixes https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/issues/683
> feat: support for exit zero sigterm

- .github/workflows/tests.yaml
Either the runner code doesn't clean up after itself, we're not cleaning up after ourselves, or we're just not giving the runner enough disk space. As a result, we're seeing out of space errors.
This addition will help diagnose the situation.
> chore: report disk usage in test run

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
Adds a new flag `min-sigterm-delay` which allows the client proxy to continue accepting new connections for a specified period of time after receiving a TERM signal. This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2266.
Fixes #670
> feat: support for min-sigterm-delay

- internal/proxy/fuse_test.go
- internal/proxy/proxy_other.go
Port of Cloud SQL's https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2257.
Fixes https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/issues/666
> feat: exit when FUSE errors on accept

- .github/workflows/codeql.yml
- .github/workflows/cover.yaml
- .github/workflows/govulncheck.yaml
- .github/workflows/lint.yaml
- .github/workflows/sample-tests.yaml
- .github/workflows/tests.yaml
The custom runner persists between runs and as a result never cleans up Go modules. As a result, the Go mod cache grows and grows and grows, which eventually results in out of disk space errors. Rather than keep bumping the disk size, this PR disables the cache such that a test run doesn't leave a big footprint behind.
Fixes #696.
> chore: resolve out of disk space errors

- cmd/root.go
- cmd/root_test.go
Fix the issue https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/issues/725
> feat: accept GET method at /quitquitquit

- .github/release-please.yml
This commit ensures we don't need to manually update the version in the generated docs.
> chore: release-please updates the generated docs

- internal/proxy/proxy_test.go
This commit retries the dialer a few times to handle the case where a client has connected but has not yet dialed the remote instance, while the test has already asserted the dialer should have run.
Fixes #551
> chore: fix flaky client initialization test

- cmd/root_test.go
Windows test runs are failing frequently, presumably because shutting down the HTTP server and releasing the port takes longer than macOS or Linux.
This commit is a simple fix and uses separate ports to avoid collision.
Fixes #739
> chore: use separate ports for QuitQuitQuit tests

- .github/workflows/codeql.yml
- .github/workflows/cover.yaml
- .github/workflows/govulncheck.yaml
- .github/workflows/lint.yaml
- .github/workflows/sample-tests.yaml
- .github/workflows/tests.yaml
- go.mod
Go 1.24 was released, see https://go.dev/doc/go1.24.
Fixes #756
> chore: update to Go 1.24

- cmd/root.go
- docs/cmd/alloydb-auth-proxy.md
Fixes #777 - removing references to `min-ready` to prevent confusion for users.
> docs: remove mentions of min-ready
